# Generated by Django 3.0.5 on 2020-06-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
    ]
