# Generated by Django 3.0.5 on 2020-05-07 13:09

from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30, unique=True)),
                ('branch_address', models.CharField(max_length=50)),
                ('branch_phone_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('branch_des', models.TextField()),
                ('branch_pic', models.ImageField(blank=True, upload_to='img/')),
                ('branch_created_at', models.DateTimeField(auto_now_add=True)),
                ('branch_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.AutoField(primary_key=True, serialize=False)),
                ('courier_name', models.CharField(help_text='Enter name of courier ', max_length=100)),
                ('courier_des', models.TextField(help_text='Notes about Courier')),
                ('courier_sending_branch', models.ManyToManyField(to='courier_branch.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='CourierDetails',
            fields=[
                ('courier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='courier_branch.Courier')),
                ('courier_tracking_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('courier_sending_person', models.CharField(max_length=100)),
                ('courier_receiving_person', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_status', models.CharField(default='Pending', max_length=9)),
                ('receiving_branch', models.ManyToManyField(to='courier_branch.Branch')),
            ],
            options={
                'ordering': ['received_at'],
            },
            bases=('courier_branch.courier',),
        ),
    ]
