# Generated by Django 3.0.5 on 2020-05-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_name',
            field=models.CharField(help_text='Enter name of courier', max_length=100, unique=True),
        ),
    ]
