# Generated by Django 3.0.5 on 2020-05-30 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_branch', '0003_auto_20200516_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_pic',
            field=models.ImageField(blank=True, upload_to='branch/'),
        ),
    ]
