# Generated by Django 3.0.5 on 2020-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier_branch', '0004_auto_20200530_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Your name', max_length=20)),
                ('feedback', models.CharField(help_text='Enter Your feedback', max_length=200)),
                ('your_picture', models.ImageField(blank=True, upload_to='comment/')),
                ('comment_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
