# Generated by Django 3.0.5 on 2020-06-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier_branch', '0006_daybook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayBook',
        ),
    ]
