# Generated by Django 3.0.5 on 2020-06-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier_branch', '0008_daybook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daybook',
            old_name='balance',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='daybook',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier_branch.Branch'),
        ),
    ]
